spring:
  application:
    name: assignment

  datasource:
    url: jdbc:postgresql://baithak-db-baithakassi.c.aivencloud.com:25325/defaultdb?ssl=require
    username: avnadmin
    password: AVNS_FrR2dDp7cm-QZ3xK3ee
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.baithak.assignment: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/assignment.log
